from __future__ import annotations

from copy import deepcopy
from typing import Any

ALL_USER_PERMISSIONS = [
    "dashboard",
    "sales_documents",
    "purchases_inventory",
    "customers_vendors",
    "reports_settings",
]

ROLE_PERMISSION_PRESETS: dict[str, list[str]] = {
    "owner": ALL_USER_PERMISSIONS,
    "employee": ["dashboard", "sales_documents", "customers_vendors"],
}

LEGACY_ROLE_MAP = {
    "admin": "employee",
    "manager": "employee",
    "accountant": "employee",
    "sales": "employee",
    "purchasing": "employee",
    "inventory": "employee",
    "staff": "employee",
    "viewer": "employee",
}

LEGACY_PERMISSION_GROUPS = {
    "view_dashboard": "dashboard",
    "manage_company_profile": "reports_settings",
    "manage_document_settings": "reports_settings",
    "manage_users_roles": "reports_settings",
    "view_documents": "sales_documents",
    "create_documents": "sales_documents",
    "edit_documents": "sales_documents",
    "delete_documents": "sales_documents",
    "approve_documents": "sales_documents",
    "send_share_documents": "sales_documents",
    "view_customers": "customers_vendors",
    "manage_customers": "customers_vendors",
    "view_products_services": "purchases_inventory",
    "manage_products_services": "purchases_inventory",
    "view_reports": "reports_settings",
    "manage_currency_settings": "reports_settings",
}

SETTINGS_DEFAULTS: dict[str, dict[str, Any]] = {
    "company": {
        "name": "Siam Tech Co., Ltd.",
        "taxId": "0105561234567",
        "branch": "Head Office (00000)",
        "address": "123 Sukhumvit Rd., Klongtoey, Bangkok 10110",
        "phone": "02-123-4567",
        "email": "info@siamtech.co.th",
        "contactName": "Accounting Team",
        "website": "https://siamtech.example",
        "vatRegistrationMode": "registered",
        "taxDefaults": {
            "vatRate": 7.0,
            "taxMode": "exclusive",
            "withholdingRate": 3.0,
        },
        "bankAccounts": [
            {
                "id": "BANK-001",
                "bankName": "Bangkok Bank",
                "accountName": "Siam Tech Co., Ltd.",
                "accountNumber": "123-4-56789-0",
                "branch": "Sukhumvit",
                "promptPayId": "",
                "swiftCode": "BKKBTHBK",
                "isDefault": True,
            }
        ],
    },
    "users": {
        "inviteMessage": "Invite teammates to collaborate on setup, documents, and reporting.",
        "members": [
            {
                "id": "USR-001",
                "name": "Aimmy Admin",
                "email": "aimmy@example.com",
                "role": "owner",
                "status": "active",
                "lastSeen": "Online now",
                "permissions": ROLE_PERMISSION_PRESETS["owner"],
            },
            {
                "id": "USR-002",
                "name": "Niran Finance",
                "email": "niran@example.com",
                "role": "employee",
                "status": "active",
                "lastSeen": "2 hours ago",
                "permissions": ["dashboard", "sales_documents", "purchases_inventory", "reports_settings"],
            },
            {
                "id": "USR-003",
                "name": "Somchai Bunnak",
                "email": "somchai@siamtech.co.th",
                "role": "employee",
                "status": "active",
                "lastSeen": "Online now",
                "permissions": ROLE_PERMISSION_PRESETS["employee"],
            },
        ],
        "permissionNotes": [
            "Owner has full access.",
            "Documents created by employees require owner approval.",
            "Only owners can change roles, permissions, and invitation actions.",
        ],
    },
    "documents": {
        "headerTitle": "Tax Invoice",
        "quotationHeaderTitle": "Quotation",
        "receiptHeaderTitle": "Receipt",
        "footerNote": "Generated by Matter Acc.",
        "defaultTerms": "Payment due within 14 days unless otherwise agreed.",
        "taxMode": "exclusive",
        "showSignatureLine": True,
        "perLineVat": False,
        "perLineDiscount": True,
        "showWhtFooter": False,
        "perLineWithholdingTax": False,
        "receiptAdjustmentFooter": False,
        "accountantExpenseCategory": True,
        "compactReceiptMode": False,
    },
    "taxes": {
        "vatRegistered": True,
        "vatRate": 7.0,
        "outputTaxRecognition": "invoice",
        "inputTaxRecognition": "expense",
        "stockDeductionTiming": "invoice",
        "lockDocumentsAfterPayment": True,
        "receiptVariant": "tax-receipt",
        "withholdingEnabled": False,
        "withholdingRate": 3.0,
    },
    "branding": {
        "logoUrl": "",
        "logoPath": "",
        "logoContentType": "",
        "stampUrl": "",
        "stampPath": "",
        "stampContentType": "",
        "signatureUrl": "",
        "signaturePath": "",
        "signatureContentType": "",
        "signatureLabel": "Authorized Signature",
        "stampLabel": "Company Stamp",
        "accentColor": "#1d4ed8",
        "documentTagline": "Accounting workflows for modern Thai SMEs",
    },
    "numbering": {
        "mode": "yearly_reset",
        "serialDigits": 4,
        "invoicePrefix": "INV",
        "quotationPrefix": "QT",
        "receiptPrefix": "RC",
        "purchaseOrderPrefix": "PO",
        "receivePrefix": "REC",
        "expensePrefix": "EXP",
        "invoiceHeader": "Tax Invoice",
        "quotationHeader": "Quotation",
        "receiptHeader": "Receipt",
        "purchaseOrderHeader": "Purchase Order",
        "receiveHeader": "Goods Received",
        "expenseHeader": "Expense",
        "backdatedInsertionWarning": "Backdated documents keep their own date-based sequence bucket. Existing issued numbers are not renumbered.",
    },
    "currency": {
        "baseCurrency": "THB",
        "multiCurrencyEnabled": False,
        "defaultExchangeRate": 1.0,
        "enabledCurrencies": ["THB"],
        "exchangeRateSource": "manual",
        "manualRates": {
            "THB": 1.0,
            "USD": 36.25,
            "EUR": 39.4,
        },
        "documentSnapshot": {
            "useDocumentDate": True,
            "fallbackRate": 1.0,
            "note": "Rates are snapped at document creation time and stored with the document.",
        },
    },
    "integrations": {
        "bankFeedsEnabled": False,
        "emailDeliveryEnabled": True,
        "eTaxEnabled": False,
        "genericApi": {
            "baseUrl": "",
            "apiKeyLabel": "",
            "webhookSecretLabel": "",
            "notes": "",
        },
        "connections": [
            {
                "key": "shopee",
                "name": "Shopee",
                "description": "Import marketplace orders and settlement data.",
                "status": "needs_configuration",
                "category": "marketplace",
                "importMode": "sales_documents",
                "lastSync": "",
                "config": {"merchantId": "", "apiKeyLabel": "", "notes": ""},
            },
            {
                "key": "lazada",
                "name": "Lazada",
                "description": "Sync marketplace sales into document import flows.",
                "status": "disconnected",
                "category": "marketplace",
                "importMode": "sales_documents",
                "lastSync": "",
                "config": {"merchantId": "", "apiKeyLabel": "", "notes": ""},
            },
            {
                "key": "foodstory",
                "name": "FoodStory",
                "description": "Bring POS sales summaries into the import workspace.",
                "status": "needs_configuration",
                "category": "pos",
                "importMode": "sales_documents",
                "lastSync": "",
                "config": {"branchCode": "", "apiKeyLabel": "", "notes": ""},
            },
            {
                "key": "wongnai_pos",
                "name": "Wongnai POS",
                "description": "Prepare branch-level sales imports from Wongnai POS.",
                "status": "disconnected",
                "category": "pos",
                "importMode": "sales_documents",
                "lastSync": "",
                "config": {"branchCode": "", "apiKeyLabel": "", "notes": ""},
            },
            {
                "key": "grabfood",
                "name": "GrabFood",
                "description": "Connection shell for delivery settlement imports.",
                "status": "coming_soon",
                "category": "delivery",
                "importMode": "sales_documents",
                "lastSync": "",
                "config": {"merchantId": "", "apiKeyLabel": "", "notes": ""},
            },
            {
                "key": "lineman",
                "name": "Lineman",
                "description": "Route delivery settlement data into import review.",
                "status": "coming_soon",
                "category": "delivery",
                "importMode": "sales_documents",
                "lastSync": "",
                "config": {"merchantId": "", "apiKeyLabel": "", "notes": ""},
            },
            {
                "key": "foodpanda",
                "name": "Foodpanda",
                "description": "Configure Foodpanda payout and sales import mapping.",
                "status": "disconnected",
                "category": "delivery",
                "importMode": "sales_documents",
                "lastSync": "",
                "config": {"merchantId": "", "apiKeyLabel": "", "notes": ""},
            },
            {
                "key": "line_shopping",
                "name": "Line Shopping",
                "description": "Prepare chat-commerce order imports and reconciliation.",
                "status": "needs_configuration",
                "category": "marketplace",
                "importMode": "sales_documents",
                "lastSync": "",
                "config": {"merchantId": "", "apiKeyLabel": "", "notes": ""},
            },
            {
                "key": "etax_email",
                "name": "e-Tax by Email",
                "description": "Store sender/config details for future e-tax delivery.",
                "status": "connected",
                "category": "tax",
                "importMode": "",
                "lastSync": "2026-04-19 09:10",
                "config": {"senderEmail": "tax@siamtech.co.th", "certificateLabel": "Production certificate", "notes": ""},
            },
            {
                "key": "generic_api",
                "name": "Generic API Connector",
                "description": "Fallback connector shell for custom imports and webhooks.",
                "status": "needs_configuration",
                "category": "api",
                "importMode": "sales_documents",
                "lastSync": "",
                "config": {"baseUrl": "", "apiKeyLabel": "", "notes": ""},
            },
        ],
    },
}


SETTINGS_SECTIONS = tuple(SETTINGS_DEFAULTS.keys())


def get_setting_defaults(section: str) -> dict[str, Any]:
    if section not in SETTINGS_DEFAULTS:
        raise ValueError(f"Unsupported settings section: {section}")
    return deepcopy(SETTINGS_DEFAULTS[section])


def merge_settings_section(section: str, payload: dict[str, Any] | None) -> dict[str, Any]:
    merged = get_setting_defaults(section)
    if payload:
        for key, value in payload.items():
            if value is not None:
                if isinstance(value, dict) and isinstance(merged.get(key), dict):
                    merged[key] = {**merged[key], **value}
                else:
                    merged[key] = value
    if section == "users":
        normalized_members = []
        for member in merged.get("members", []):
            if not isinstance(member, dict):
                continue
            role = str(member.get("role") or "employee").strip().lower()
            role = LEGACY_ROLE_MAP.get(role, role)
            if role not in ROLE_PERMISSION_PRESETS:
                role = "employee"
            permissions = member.get("permissions")
            if role == "owner":
                permissions = ROLE_PERMISSION_PRESETS[role]
            elif not isinstance(permissions, list):
                permissions = ROLE_PERMISSION_PRESETS[role]
            else:
                allowed = set(ALL_USER_PERMISSIONS)
                normalized_permissions = []
                for permission in permissions:
                    normalized_permission = LEGACY_PERMISSION_GROUPS.get(str(permission), str(permission))
                    if normalized_permission in allowed and normalized_permission not in normalized_permissions:
                        normalized_permissions.append(normalized_permission)
                permissions = normalized_permissions
            normalized_members.append(
                {
                    **member,
                    "role": role,
                    "permissions": permissions,
                }
            )
        if normalized_members and not any(member.get("role") == "owner" for member in normalized_members):
            normalized_members[0]["role"] = "owner"
            normalized_members[0]["permissions"] = ROLE_PERMISSION_PRESETS["owner"]
        merged["members"] = normalized_members
    return merged


def normalize_settings(settings: dict[str, Any] | None) -> dict[str, dict[str, Any]]:
    resolved_settings = settings if isinstance(settings, dict) else {}
    return {
        section: merge_settings_section(section, resolved_settings.get(section))
        for section in SETTINGS_SECTIONS
    }


def build_policy_snapshot(settings: dict[str, Any] | None) -> dict[str, Any]:
    normalized = normalize_settings(settings)
    taxes = normalized["taxes"]
    company = normalized["company"]
    currency = normalized["currency"]
    numbering = normalized["numbering"]
    documents = normalized["documents"]

    return {
        "vatRegistered": bool(taxes["vatRegistered"]) and company.get("vatRegistrationMode") != "not_registered",
        "vatRate": round(float(taxes["vatRate"]) / 100, 4),
        "outputTaxRecognition": taxes["outputTaxRecognition"],
        "inputTaxRecognition": taxes["inputTaxRecognition"],
        "stockDeductionTiming": taxes["stockDeductionTiming"],
        "lockDocumentsAfterPayment": bool(taxes["lockDocumentsAfterPayment"]),
        "receiptVariant": taxes["receiptVariant"],
        "withholdingEnabled": bool(taxes["withholdingEnabled"]),
        "withholdingRate": round(float(taxes["withholdingRate"]) / 100, 4),
        "baseCurrency": currency["baseCurrency"],
        "multiCurrencyEnabled": bool(currency["multiCurrencyEnabled"]),
        "defaultExchangeRate": float(currency["defaultExchangeRate"]),
        "numbering": deepcopy(numbering),
        "documents": deepcopy(documents),
    }
